# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0014_auto_20160404_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonicNotebookConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Config name', max_length=32, verbose_name=b'Name')),
                ('script_block', models.CharField(default=b'js', help_text='Script block', max_length=32, verbose_name=b'Script block')),
            ],
            options={
                'verbose_name': 'Tonic notebook config',
                'verbose_name_plural': 'Tonic notebook configs',
            },
        ),
        migrations.CreateModel(
            name='TonicNotebookPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('code', models.TextField(default=b'', help_text='Source code', verbose_name=b'Source code')),
                ('readonly', models.BooleanField(default=True, help_text='Is readonly', verbose_name=b'Readonly')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_tonicdev.TonicNotebookConfigModel', verbose_name='Notebook config')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
