# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_tonicdev', '0002_tonicnotebookpluginmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonicnotebookpluginmodel',
            name='readonly',
            field=models.BooleanField(default=False, help_text='Is readonly', verbose_name=b'Readonly'),
        ),
    ]
