# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_tonicdev', '0004_auto_20160509_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonicnotebookconfigmodel',
            name='node_version',
            field=models.CharField(blank=True, help_text='Provide a semver range that the node engine should satisfy, e.g. 0.12.x or > 4.0.0', max_length=32, null=True, verbose_name=b'Node version'),
        ),
    ]
